services:
  rahoot:
    build: .
    image: rahoot:latest
    volumes:
      - ./config:/app/config # Path to your game config
    environment:
      - WEB_ORIGIN=${WEB_ORIGIN:-https://your-domain.com}
      - SOCKET_URL=${SOCKET_URL:-https://your-domain.com}

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - rahoot
